### PR TITLE
fix/configurable-client-request-timeout

### PR DESCRIPTION
**Pull request by albertlabarentojr**
- Added config
- connection_timeout = ELASTICSEARCH_CONNECTION_TIMEOUT, default: 2
- timeout = ELASTICSEARCH_TIMEOUT, default: 12

### CODE REVIEW

**Comment by sjdaws** [comment]
Hi @AlbertLabarento 

This won't be merged since it contains a global helper method. My suggestion is to copy or extend the service provider into your application and set the configuration there.

Scott.

**Comment by albertlabarentojr** [comment]
Hi @sjdaws,

But `\env()` was already used from the given code and we can't extend because the service provider is a final class :) . Thanks

https://github.com/AlbertLabarento/search/blob/5d7403babfd22070b20b5fc03c2e5142843a8e1c/src/Bridge/Laravel/Providers/SearchServiceProvider.php#L114

Albert

**Comment by natepage** [comment]
@sjdaws As @AlbertLabarento said the `\env()` function is already used in this class so don't really understand why using it for those config values is an issue.

```php
->setHosts(\array_filter([(string)\env('ELASTICSEARCH_HOST', '')]))
->setSSLVerification((bool)\env('ELASTICSEARCH_VERIFY_SSL', true))
```

And copying the service provider in our application will defeat the purpose of reusable packages as we will miss the updates made to this class and will have to maintain it ourselves.

**Comment by natepage** [comment]
Also in my opinion we should use `\config()` and introduce a default config file which uses `\env()` so this way the applications don't necessarily have to use env variables to set them.

**Pull request merged**
